//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBEAccounts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataKeyValue
    {
        public int Id { get; set; }
        public string DataKey { get; set; }
        public int DataValue { get; set; }
        public int CompanyId { get; set; }
    }
}
