//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBEAccounts.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public double OpeningStock { get; set; }
        public double ReorderLevel { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
        public virtual Product Product { get; set; }
    }
}
