//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NUBEAccounts.Message {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NUBEAccounts.Message.PL", typeof(PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Could not be Deleted!.
        /// </summary>
        public static string Cant_Delete_Alert {
            get {
                return ResourceManager.GetString("Cant_Delete_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Successfully.
        /// </summary>
        public static string Delete_Alert {
            get {
                return ResourceManager.GetString("Delete_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to Delete this record?.
        /// </summary>
        public static string Delete_confirmation {
            get {
                return ResourceManager.GetString("Delete_confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission to Delete the {0}.
        /// </summary>
        public static string DenyDelete {
            get {
                return ResourceManager.GetString("DenyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission to view the {0}.
        /// </summary>
        public static string DenyFormShow {
            get {
                return ResourceManager.GetString("DenyFormShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission to Insert  the {0}.
        /// </summary>
        public static string DenyInsert {
            get {
                return ResourceManager.GetString("DenyInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Permission to Update the {0}.
        /// </summary>
        public static string DenyUpdate {
            get {
                return ResourceManager.GetString("DenyUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is Empty!.
        /// </summary>
        public static string Empty_Record {
            get {
                return ResourceManager.GetString("Empty_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Already Exist..
        /// </summary>
        public static string Existing_Data {
            get {
                return ResourceManager.GetString("Existing_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Company!.
        /// </summary>
        public static string Login_CompanyName_Validation {
            get {
                return ResourceManager.GetString("Login_CompanyName_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Dealer !.
        /// </summary>
        public static string Login_Dealer_Validation {
            get {
                return ResourceManager.GetString("Login_Dealer_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Password !.
        /// </summary>
        public static string Login_Password_Validation {
            get {
                return ResourceManager.GetString("Login_Password_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Username !.
        /// </summary>
        public static string Login_UserName_validation {
            get {
                return ResourceManager.GetString("Login_UserName_validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter warehouse !.
        /// </summary>
        public static string Login_Warehouse_Validation {
            get {
                return ResourceManager.GetString("Login_Warehouse_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password_Exist!.
        /// </summary>
        public static string Password_Exist {
            get {
                return ResourceManager.GetString("Password_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Stock {0}.
        /// </summary>
        public static string Product_Available_Stock {
            get {
                return ResourceManager.GetString("Product_Available_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnAvailable Stock.
        /// </summary>
        public static string Product_Not_In_Stock {
            get {
                return ResourceManager.GetString("Product_Not_In_Stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved Successfully.
        /// </summary>
        public static string Saved_Alert {
            get {
                return ResourceManager.GetString("Saved_Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Customer!.
        /// </summary>
        public static string Transaction_Empty_Customer {
            get {
                return ResourceManager.GetString("Transaction_Empty_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product.
        /// </summary>
        public static string Transaction_Empty_Product {
            get {
                return ResourceManager.GetString("Transaction_Empty_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Supplier!.
        /// </summary>
        public static string Transaction_Empty_Supplier {
            get {
                return ResourceManager.GetString("Transaction_Empty_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Product Detail.
        /// </summary>
        public static string Transaction_ItemDetails_Validation {
            get {
                return ResourceManager.GetString("Transaction_ItemDetails_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job has been Received!.
        /// </summary>
        public static string Transaction_Job_Received {
            get {
                return ResourceManager.GetString("Transaction_Job_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Done!!.
        /// </summary>
        public static string Transaction_Make_Purchase {
            get {
                return ResourceManager.GetString("Transaction_Make_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Done!!.
        /// </summary>
        public static string Transaction_Make_Sales {
            get {
                return ResourceManager.GetString("Transaction_Make_Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, Not Found !.
        /// </summary>
        public static string Transaction_Not_Fount {
            get {
                return ResourceManager.GetString("Transaction_Not_Fount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter {0}!.
        /// </summary>
        public static string Transaction_POcode {
            get {
                return ResourceManager.GetString("Transaction_POcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Rate Between {0} to {1}.
        /// </summary>
        public static string Transaction_Selling_Rate {
            get {
                return ResourceManager.GetString("Transaction_Selling_Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId Already Exist!.
        /// </summary>
        public static string User_Id_Exist {
            get {
                return ResourceManager.GetString("User_Id_Exist", resourceCulture);
            }
        }
    }
}
